### PR TITLE
AWS Lambda integration fails to detect the aws-lambda-ric 1.0 bootstrap

### PR DESCRIPTION
**Pull request by adam-olema**
Fix for https://github.com/getsentry/sentry-python/issues/972

### CODE REVIEW

**Comment by adam-olema** [comment]
Don't know how to get the aws lambda tests to actually run.  Until then, the coverage test will not pass.

**Comment by untitaker** [comment]
@adam-olema the AWS lambda tests run against a real instance and as such require credentials that are not available for PRs of forks.

Can you add a comment indicating why this is necessary? A hint at aws-lambda-ric suffices.

**Comment by adam-olema** [comment]
Under normal documented usage, with the current aws-lambda-ric 1.0, without this change, you only get the following warning, and no errors sent to sentry:

    Not running in AWS Lambda environment, AwsLambdaIntegration disabled (could not find handle_event_request)

So, not sure what changed, but in my setup at least, the sentry library does not detect the AWS lambda runtime at all.  It may have to do with the structure of my application which places the main handler not at the top level module but in a submodule (ie: not the usual my_app.handler, but instead my_app.sub_module.handler

**Comment by untitaker** [comment]
@adam-olema I understand, I am asking that you put this as code comment, to be clear

**Comment by adam-olema** [comment]
> @adam-olema I understand, I am asking that you put this as code comment, to be clear

Gotcha.  Comment added.

**Comment by untitaker** [comment]
Thanks!

**Pull request merged**
