### PR TITLE
Add option to specify client certificate

### PR DESCRIPTION
**Pull request by maresac**
See [urllib3 docs](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#custom-ssl-certificates-and-client-certificates)

### CODE REVIEW

**Comment by maresac** [comment]
Is there a possibility to re-run the pipeline without exceeding the API rate limit?

**Comment by untitaker** [comment]
Sorry about that CI failure, will fix.

Did you manage to do something similar in Raven? We're a bit hesitant to support this as it's not a popular usecase and would prefer if you subclassed the `HTTPTransport` class yourself to provide this functionality.

Right now that class is not very flexible but I'll prepare another PR for that

**Comment by untitaker** [comment]
Could you check if this fits your usecase? https://github.com/getsentry/sentry-python/pull/235

**Comment by ckoehn** [comment]
This will definitely work, but still sad that you don't want to support a feature which can be implemented by just adding 4 lines of code.

**Comment by untitaker** [comment]
@ckoehn The reason I want to avoid having more options on the client is that we try to align those across SDKs. There are many options on `urllib3.PoolManager` that might be useful to some people (connection timeouts?), but adding individual support for each of them ends up being a lot of code.

Using a client certificate to authenticate the SDK against the server is very non-standard. The "auth" mechanism we intended for people to use was the key in the DSN. Let's say somebody added something to their nginx/apache cfg to check for HTTP Basic auth header. Would you expect me to merge the PR that adds corresponding username/password options to the SDK?

**Comment by ckoehn** [comment]
Fair point. You didn't mention that you want to align the options across SDKs and I was just curious why you rejected such a simple change :wink:

**Pull request closed without merging**
