### PR TITLE
Rework proxy selection 

### LINKED ISSUE #178: Send events without proxy  when http_proxy is configured as env variable
Hi,
I have problem with configuration of sentry_sdk. My code is behind corporate proxy and `http_proxy` is configured on machine as env variable (required when I want to install something via pip for example). Also I have env variable `no_proxy` where I added ip address for host where sentry is working (this ip is inside corporate network). When I try send event to sentry I got return code 403 (proxy refuse request). Probably sentry_sdk automacally fetch proxy from http_proxy env but ignore no_proxy. When I remove http_proxy from env everything is working. How can I configure python_sdk to ignore my http_proxy env variable? My code: 

```
import logging
import sentry_sdk
from sentry_sdk.integrations.logging import LoggingIntegration


sentry_logging = LoggingIntegration(
    level=logging.INFO,       
    event_level=logging.ERROR 
)
sentry_sdk.init(
    dsn="<dsn>",
    integrations=[sentry_logging],
    debug=True,
)
```

### LINKED ISSUE #308: Clarify proxy fallback behavior
I am currently working on #178 and extended the tests for the proxy selection mechanism, especially when the env variables like `HTTP_PROXY` and `HTTPS_PROXY` are present. One thing that I've observed is the fallback behavior:

- no ENV vars: HTTPS DSNs can fallback to HTTP proxies (see [test](https://github.com/getsentry/sentry-python/blob/master/tests/test_client.py#L47-L48))
- only `HTTP_PROXY` env var: no fallback for HTTPS DSNs, i.e. no proxy is auto-selected

Is that behavior intended or a bug? In either case, my PR for #178 will also include tests (and potential fixes) for that.

### PR DESCRIPTION
**Pull request by crepererum**
Fixes #308 
Fixes #178

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks for this! Since we try to have this interface aligned across SDKs I'll discuss this with the other SDK maintainers first.

**Comment by crepererum** [comment]
@untitaker are there any updates on that?

**Comment by untitaker** [comment]
@crepererum I forgot to start the discussion at the last meeting, sorry. We have a meeting every monday (so, today again) where I will bring this up, but please note that this is quite low-priority for us and we can't force a decision "at gunpoint".

**Comment by untitaker** [comment]
To be clear, I see two versions:

* ```init(http_proxy=False, https_proxy=False)```

* ```init(no_proxy=True)```

**Comment by untitaker** [comment]
Sorry, we have an update now: Could you use empty string to represent `False`? We want to port this behavior to other languages and there we can't replicate this type signature.

**Comment by crepererum** [comment]
Done. Build failure seems unrelated (pip doesn't like pyproject.toml and editable installs)

**Comment by untitaker** [comment]
I made a PR: #349

**Comment by untitaker** [comment]
Thanks! I am quite sorry for the dragging response. It's been a few busy weeks.

**Comment by untitaker** [comment]
Released 0.7.12 with this fix (soon)

**Comment by rmk135** [comment]
Has this been already released to PyPI?

**Comment by untitaker** [comment]
@rmk135, yes, 0.7.12 is on pypi. We're on 0.14 right now

**Comment by rmk135** [comment]
and it's in `0.14.4` since yesterday, right?

**Comment by untitaker** [comment]
this was merged in 0.7.12. 0.7.12 is on pypi since april last year. 0.14.4 contains the same change.

**Comment by rmk135** [comment]
Right. Sorry, I got messed up something with something :) Thanks for the help.

**Pull request merged**
