### PR TITLE
ref(client): Improve `get_integration` typing

### PR DESCRIPTION
**Pull request by szokeasaurusrex**
Improve `get_integration` typing to make it clear that we return an `Optional[Integration]`. Further, add overloads to specify that when called with some integration type `I` (i.e. `I` is a subclass of `Integration`), then `get_integration` guarantees a return value of `Optional[I]`.

These changes should enhance type safety by explicitly guaranteeing the existing behavior of `get_integration`.

### CODE REVIEW

**Comment by szokeasaurusrex** [comment]
@sentrivana yep still working on fixing mypy, will mark as draft until this is ready to be reviewed. I think the cleanest solution will be to replace `@ensure_integration_enabled` with the old manual checking that the integration is not `None` whenever we need to access the `Integration` object, because this allows `mypy` to recognize that the integration object cannot be `None`. 

We can still use `@ensure_integration_enabled` anywhere we don't need to access the `Integration` object

**Comment by szokeasaurusrex** [comment]
The `mypy` errors led me to find a couple places where we were not checking that the integration was still enabled, so I think this change will potentially help us avoid making such mistakes in the future

**Review by sentrivana — APPROVED** [review]
Are we still using `ensure_integration_enabled` after this? If not, we can remove it.

**Comment by szokeasaurusrex** [comment]
@sentrivana, yeah we are; I found ca. 100 usages after these changes. `@ensure_integration_enabled` is still helpful anytime we don't need access to the integration object within the patched function, which is quite often apparently. However, it is less useful when we need the integration object, since we anyways need to check whether the integration object is `None` in order to ensure type safety

**Pull request merged**
