### PR TITLE
Remove outdated pins

### PR DESCRIPTION
**Pull request by sentrivana**
Remove version pins on tools that are no longer necessary.

Relates https://github.com/getsentry/sentry-python/issues/2586

---

## General Notes

Thank you for contributing to `sentry-python`!

Please add tests to validate your changes, and lint your code using `tox -e linters`.

Running the test suite on your PR might require maintainer approval. Some tests (AWS Lambda) additionally require a maintainer to add a special label to run and will fail if the label is not present.

#### For maintainers

Sensitive test suites require maintainer review to ensure that tests do not compromise our secrets. This review must be repeated after any code revisions.

Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before running sensitive tests.

### CODE REVIEW

**Comment by antonpirker** [comment]
I just ran the tests locally and there is no error. Just the `tests/integrations/django/asgi/test_asgi.py` tests in the Django test suite freeze and thus the test suite times out. So something with async stuff is off.

**Comment by sentrivana** [comment]
> I just ran the tests locally and there is no error. Just the `tests/integrations/django/asgi/test_asgi.py` tests in the Django test suite freeze and thus the test suite times out. So something with async stuff is off.

Yeah this. Also works for me locally. Interestingly, it only fails on 3.12, but it's not some dependency issue because it installs the same versions of the same dependencies on both 3.11 (where it's working) and 3.12.

Will try to bisect a bit what is causing this.

**Comment by sentrivana** [comment]
So it works with `tox<4`, but anything higher than that makes the async django tests hang in CI.

Will spend a bit more time trying to figure this out. But even if I can't and we have to keep tox pinned on 3.12 for now, we can merge this, since it still removes a ton of other pins.

**Comment by antonpirker** [comment]
Very cool work @sentrivana ! I can also try to spend some time tomorrow to help with this.
Bringing our tooling kind of up to date is long time over due :-)

**Comment by antonpirker** [comment]
I just messed around with the Django tests. The problem is the following:
- We have this "Web Frameworks 1" test suite that runs multiple test suites in a matrix. 
- Every test suite uses the[ service "postgres"](https://github.com/getsentry/sentry-python/blob/antonpirker/tooling/.github/workflows/test-integrations-web-frameworks-1.yml#L103-L117) defined in the yaml file. 
- And in this postgres service we create one database called "ci_test"
- When the first test that is decorator with `pytest_mark_django_db_decorator` is run, the database is filled by running the django migrations. 

And my guess now is that when two test suites run at the same time they both want to fill the db by running the migrations and because there is already something in the db, it fails with the `duplicate key value violates unique constraint` error.

And as so often when fixing bugs the question is: How has this ever worked at some point? :-)

Solution would now be to either have one postgres server by test suite, or one unique database name per test suite. (or maybe create the postgres server in some completely different way)

**Comment by antonpirker** [comment]
I played around more and have this: https://github.com/getsentry/sentry-python/actions/runs/8572070273/job/23493776173?pr=2938

The thing now is that in "Setup Test Env" i try to delete the uniquely named db name but it does not exist. (which is fine)  Two steps later when running the django tests they fail becaus the db is already existing. So the db is not cleaned up between running different django versions in one call to tox. Not sure why, but this is something for future Anton!

**Comment by sentrivana** [comment]
@antonpirker Maybe this can be somehow combined with `--create-db`/`--reuse-db`? https://pytest-django.readthedocs.io/en/latest/database.html#create-db-force-re-creation-of-the-test-database

```
--create-db - force re creation of the test database

When used with --reuse-db, this option will re-create the database, regardless of whether it exists or not.
```

**Comment by antonpirker** [comment]
Ok, the Python 3.12 tests still freeze, but the rest is green so I will merge it into here.

**Comment by sentrivana** [comment]
Awesome! The Web Frameworks 1 tests on 3.12 will still time out but that's not a problem with your PR. Everything else seems green so feel free to merge

**Comment by sentrivana** [comment]
Marking this as ready for review but we shouldn't merge this until the final release is out.

**Pull request merged**
