### PR TITLE
Sort breadcrumbs before sending

### LINKED ISSUE #3306: Fix Breadcrumb ordering
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

all

### Steps to Reproduce

Breadcrumbs live on the Scope. 

Before the event is sent to Sentry the list of breadcrumbs of multiple Scopes are concatenated list of breadcrumbs that is sent to Sentry.

We do not order the final breadcrumb list before sending, so all breadcrumbs of Scope A are followed by all breadcrumbs of Scope B. 

### Expected Result

The breadcrumbs should be ordered by timestamp before being sent to Sentry.

### PR DESCRIPTION
**Pull request by antonpirker**
Make sure our breadcrumbs are sorted by timestamp before sending to Sentry.

Fixes #3306

### CODE REVIEW

**Review by sentrivana — COMMENTED** [review]
The change lgtm. Can we also have a test for this or is it a pita?

**Comment by antonpirker** [comment]
I'll check

**Comment by antonpirker** [comment]
Now with test @sentrivana

**Review by sentrivana — APPROVED** [review]
Awesome, ty!

**Pull request merged**
