### PR TITLE
ref(pymongo): Change span operation from `db.query` to `db`

### PR DESCRIPTION
**Pull request by 0Calories**
The pymongo integration is the only place where span ops were being set to `db.query`, which is inconsistent with other SDKs like the Node SDK.

### CODE REVIEW

**Review by antonpirker — APPROVED** [review]
Nice! Thanks for the improvement!

**Comment by antonpirker** [comment]
You can merge this @0Calories ! Thanks!

**Comment by 0Calories** [comment]
@antonpirker Thanks! But it seems that I don't have permission to merge this in, all required checks are met and there's no option to merge 😕

**Comment by antonpirker** [comment]
Oh ok, I will merge it.

**Pull request merged**
