### PR TITLE
fix(integrations): KeyError('sentry-monitor-start-timestamp-s')

### LINKED ISSUE #3277: KeyError('sentry-monitor-start-timestamp-s')
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.8.0

### Steps to Reproduce

I had a task at the company to track **Celery** beat tasks in Sentry. This task has been completed, and **everything is working correctly**. However, with each execution of the task, an unusual exception is displayed in Sentry. This happens once every minute.
Since I set the **monitor_beat_tasks** to **True**, this event has been occurring.

This exception is handled, but It is not interesting that it is constantly displayed on sentry.

Interestingly, this does not happen in the local environment(in my laptop)! and just we have this problem on production.
My local system:
Ubuntu 22.04
Python 3.10.12
Celery 5.3.6
sentry_sdk 2.8.0

In production we using Docker and Kubernetes, we are using Python:3.10 image and packages versions are same as my local!

### Expected Result

Don't show this exception on sentry.
My task is working well and this error has made our sentry busy.

### Actual Result

Screenshot from 2024-07-10 22-42-40

Screenshot from 2024-07-10 22-43-31

Logs of celery worker in production:

```
[2024-07-10 20:51:00,088: INFO/MainProcess] Task send_concierge_sale_to_assistant_offer_task[0349add3-713c-4ff0-83b8-fecb44652ea4] received
[2024-07-10 20:51:04,561: ERROR/ForkPoolWorker-4] Signal handler <function crons_task_success at 0x7f83cc319cf0> raised: KeyError('sentry-monitor-start-timestamp-s')
2024-07-10T20:51:04.562478564Z Traceback (most recent call last):
2024-07-10T20:51:04.562484644Z   File "/usr/local/lib/python3.10/site-packages/celery/utils/dispatch/signal.py", line 276, in send
2024-07-10T20:51:04.562488411Z     response = receiver(signal=self, sender=sender, **named)
2024-07-10T20:51:04.562493177Z   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery/beat.py", line 255, in crons_task_success
2024-07-10T20:51:04.562497673Z     start_timestamp_s = float(headers["sentry-monitor-start-timestamp-s"])
2024-07-10T20:51:04.562501032Z KeyError: 'sentry-monitor-start-timestamp-s'
[2024-07-10 20:51:04,565: INFO/ForkPoolWorker-4] Task send_concierge_sale_to_assistant_offer_task[0349add3-713c-4ff0-83b8-fecb44652ea4] succeeded in 4.470669243019074s: None
```

### PR DESCRIPTION
**Pull request by Mohsen-Khodabakhshi**
I said my problem in this issue:
https://github.com/getsentry/sentry-python/issues/3277

I prefered to use .get("sentry-monitor-start-timestamp-s") to solve my problem and don't get exception.
I hope it can be useful to some extent.

Fixes #3277

### CODE REVIEW

**Review by sl0thentr0py — APPROVED** [review]
ty @Mohsen-Khodabakhshi

**Comment by szokeasaurusrex** [comment]
@sl0thentr0py @Mohsen-Khodabakhshi, we should also handle the case where the other values from the `headers` are missing. It's quite possible that if we merge this PR as is, you could get a KeyError for one of the other values, since maybe the `headers` are getting cleared somewhere.

**Comment by szokeasaurusrex** [comment]
I can take over the PR and implement these changes if you would like

**Comment by sl0thentr0py** [comment]
@szokeasaurusrex ideally this shouldn't happen at all though so I think something else might be going wrong in this function 
https://github.com/getsentry/sentry-python/blob/f534a2283ac88671149024f547ec59a6d70f715d/sentry_sdk/integrations/celery/__init__.py#L162 and swallowed silently

**Comment by szokeasaurusrex** [comment]
@sl0thentr0py interesting. Could it be that something else is just overwriting these headers, or should our SDK really be the only thing accessing them?

**Comment by sl0thentr0py** [comment]
no I don't think something's overwriting the headers, I think we don't even add our headers because that function is a mess and this with block just swallows some other exception
https://github.com/getsentry/sentry-python/blob/f534a2283ac88671149024f547ec59a6d70f715d/sentry_sdk/integrations/celery/__init__.py#L169

**Comment by Mohsen-Khodabakhshi** [comment]
The question is why this condition is ok in this function (in beat.py):
``` Python
def _setup_celery_beat_signals(monitor_beat_tasks):
    ...
    if monitor_beat_tasks: # I mean here
        task_success.connect(crons_task_success)
        task_failure.connect(crons_task_failure)
        task_retry.connect(crons_task_retry)
```

And condition is not ok in _update_celery_task_headers function(in \_\_init\_\_.py):
``` Python
def _update_celery_task_headers(original_headers, span, monitor_beat_tasks):
    ...
    with capture_internal_exceptions():
        headers = dict(
            Scope.get_isolation_scope().iter_trace_propagation_headers(span=span)
        )

        if monitor_beat_tasks: # I mean here
            headers.update(
                {
                    "sentry-monitor-start-timestamp-s": "%.9f"
                    % _now_seconds_since_epoch(),
                }
            )
        ...
``` 
It's cool that in my os I don't have any problem :)

**Comment by sl0thentr0py** [comment]
@Mohsen-Khodabakhshi just to rule it out,
is your sentry SDK config somehow different in your worker process and the process that does the beat scheduling?

**Comment by Mohsen-Khodabakhshi** [comment]
``` Python
from celery import Celery
from celery.schedules import crontab
from sentry_sdk.scrubber import EventScrubber
from sentry_sdk.integrations.celery import CeleryIntegration

from core.settings import settings
import sentry_sdk

from domains.common.services.sentry import SENTRY_DENYLIST

sentry_sdk.init(
    dsn=settings.SENTRY_URL,
    enable_tracing=True,
    traces_sample_rate=1.0,
    event_scrubber=EventScrubber(denylist=SENTRY_DENYLIST),
    integrations=[CeleryIntegration(
        monitor_beat_tasks=True,
    )]
)

celery = Celery(
    __name__,
    include=["domains.concierge_sale.tasks"],
)
celery.conf.result_backend = settings.TRADE_CELERY_RESULT_BACKEND_URL
celery.conf.broker_url = settings.TRADE_CELERY_BROKER_URL
celery.conf.beat_schedule = {
    "shop-analytics-data-every-day": {
        "task": "send_concierge_sale_to_assistant_offer_task",
        "schedule": crontab(minute="*/1"),
    },
}
celery.conf.imports = ["domains.concierge_sale.tasks"]
celery.conf.result_backend_transport_options = {
    "global_keyprefix": settings.TRADE_CELERY_TASK_DEFAULT_QUEUE,
    "visibility_timeout": 172800,
}
celery.conf.celery_task_default_queue = settings.TRADE_CELERY_TASK_DEFAULT_QUEUE
```

This is my celery_.py  file 👆
and I run Celery worker/beat using:
``` bash
celery -A core.celery_.celery worker --loglevel=info
celery -A core.celery_.celery beat --loglevel=info
```
In our production: Celery beat and Celery worker each run on separate Kubernetes pod.

**Comment by szokeasaurusrex** [comment]
Hi @Mohsen-Khodabakhshi, looks like you are initializing the SDK incorrectly. When [using the SDK with Celery Beat](https://docs.sentry.io/platforms/python/integrations/celery/crons/), the SDK needs to be initialized within a function decorated with `@signals.beat_init.connect` and `@signals.celeryd_init.connect`, like so:

```python
@signals.beat_init.connect
@signals.celeryd_init.connect
def init_sentry(**kwargs):
    sentry_sdk.init(...)
```

**Pull request merged**
