### PR TITLE
Import Markup from markupsafe

### PR DESCRIPTION
**Pull request by rco-ableton**
Fixes a `DeprecationWarning` when using Flask v2.3.0 or later (actually, it breaks completely with `flask==2.3.0`, but that's down to a mistake in the Flask project. Some tests are failing for me locally, but the same tests are failing on the `master` branch so hopefully that's just something peculiar to my machine.

See [Flask's release notes](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0) for more context.

### CODE REVIEW

**Comment by phil-airship** [comment]
Hit this issue as well, reference for change in Flask that led to this being necessary

**Comment by antonpirker** [comment]
Thanks for the fix @rco-ableton 

I have started the CI jobs, lets see if all the tests are green. (If not, could you please fix them?)

**Comment by rco-ableton** [comment]
> I have started the CI jobs, lets see if all the tests are green. (If not, could you please fix them?)

I'd be happy to if I'm able, but right now there still seem to be 10 pending checks that haven't reported their status for a while now. Are they stuck?

**Review by sentrivana — APPROVED** [review]

**Comment by sentrivana** [comment]
I've moved `markupsafe` to the `flask` extras in `setup.py`. The PR looks good and the tests are happy, so merging this now. Thanks for contributing @rco-ableton!

**Pull request merged**
