### PR TITLE
Fix bug in _update_scope()

### PR DESCRIPTION
**Pull request by vasilty**
Introduced in e680a754e4

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks, can you add a small test for this in `test_basic`?

**Comment by vasilty** [comment]
@untitaker Sure, I added the test.

**Comment by untitaker** [comment]
Thanks! Do you need a new release?

**Comment by vasilty** [comment]
We are fine waiting till the next planned one comes out. Thank you for asking.

**Pull request merged**
