### PR TITLE
feat(tooling): Enabled local linting

### PR DESCRIPTION
**Pull request by antonpirker**
To speed up development and prevent a lot of front and back with the CI linter, I added a pre-commit hook, so before one can commit something the linting (black, flake8 and mypy) will run locally to format and lint the changed files.

### CODE REVIEW

**Comment by antonpirker** [comment]
I added "pre-commit" to the test-requirements.txt, did not know where to put it.

**Comment by antonpirker** [comment]
pre-commit has a collection of ready made hooks to choose from and it is very easy to install/uninstall the hooks. So it is just for convenience and I think it is used in python projects quite frequently (at least in the project i was part of) :-)

**Review by sl0thentr0py — APPROVED** [review]

**Comment by miketheman** [comment]
Excellent addition!
Please consider adding [https://pre-commit.ci/](https://pre-commit.ci/)  so that these checks can also be automatically fixed where possible. Free for open source projects like this one!

**Comment by sl0thentr0py** [comment]
@miketheman we already had an autofix step [here](https://github.com/getsentry/sentry-python/pull/1339) but we removed it since it was flaky on external contributors' forked PRs. Not sure if `pre-commit` also works with forked PRs?

**Comment by miketheman** [comment]
I believe it does, as I use it on some of my open source projects, and it is run when people submit pull requests from their forks.

**Comment by miketheman** [comment]
This also makes the pre-commit.yaml the source of rule evaluation, vs having to maintain them in two spots - the pre-commit files and the tox config for GH Action.

**Comment by sl0thentr0py** [comment]
ok thanks! will try it out and clean this process up a bit more.

**Pull request merged**
