### PR TITLE
fix: integration with Apache Beam 2.32, 2.33 reported in #1231

### PR DESCRIPTION
**Pull request by galuszkak**

### CODE REVIEW

**Comment by galuszkak** [comment]
@AbhiPrasad fixed. I've amended existing commit so it's clean PR.

**Comment by galuszkak** [comment]
@AbhiPrasad I think failing tests are unrelated because they are failing on Sanic.

I believe this failing change is tracked here:
https://github.com/sanic-org/sanic/issues/2250

**Comment by AbhiPrasad** [comment]
Yup unrelated test failures, we will merge regardless.

**Comment by ahopkins** [comment]
> @AbhiPrasad I think failing tests are unrelated because they are failing on Sanic.
> 
> I believe this failing change is tracked here: [sanic-org/sanic#2250](https://github.com/sanic-org/sanic/issues/2250)

If the tests are failing on Sanic's behalf related to that issue, then I am assuming it must be installing latest version which requires this to be merged: https://github.com/getsentry/sentry-python/pull/1212

**Pull request merged**
