### PR TITLE
build(ci): Remove TravisCI

### PR DESCRIPTION
**Pull request by billyvg**
Travis sprung some surprise billing changes on us, so we are now prioritizing removing TravisCI completely.

### CODE REVIEW

**Comment by billyvg** [comment]
@untitaker Aside from zeus, do you see anything missing here?

**Comment by untitaker** [comment]
@billyvg lgtm, feel free to remove ppc.

wrt zeus I will ask what other SDKs are doing right now

**Comment by jan-auer** [comment]
@billyvg thanks for getting this started! I'll engage with you on this a little later. We should migrate to GH artifacts and the new publish actions like in `sentry-javascript`. 

Would you mind if I propose a few simplifications to the CI setup, mostly consolidating most jobs in a single workflow? We've preferred that over too many workflows in the other SDKs and services that we have migrated so far.

**Comment by billyvg** [comment]
@jan-auer Sounds good!

**Comment by jan-auer** [comment]
Took the liberty to push a few changes directly to this branch:
- Use GitHub artifacts instead of Zeus, compatible with craft
- Change the craft status provider to GitHub
- No longer upload coverage anywhere other than codecov
- Add the current form of the release/publish action. It will be simplified pretty soon.
- Change the bump-version script so it warns when run from macOS (our usual approach atm).

@billyvg This is G2G from my end, thanks for doing the heavy lifting!

**Review by untitaker — APPROVED** [review]

**Comment by untitaker** [comment]
going to trust jan that the release workflow works

**Comment by billyvg** [comment]
@untitaker is it expected that 3.8 and 3.9 are failing?

**Comment by untitaker** [comment]
no. I will take a look tomorrow

**Comment by jan-auer** [comment]
Just noticed that I accidentally removed the build step for dists. 

@untitaker is the intention to always build the dist or just on the release branch?

**Comment by untitaker** [comment]
@jan-auer 

1. we can only build on release branch
2. we still support python 2 in the sdk, and venv does not work on python 2

**Comment by billyvg** [comment]
Thanks @jan-auer for rm'ing zeus.

And thanks @untitaker, can you take over this PR from here?

**Comment by jan-auer** [comment]
FWIW, 3.8 and 3.9 are failing on master already, so we can also merge as is and tackle the fixes in a follow-up.

**Comment by jan-auer** [comment]
That said, on the last two builds we received timeouts for the 3.7 test job:

> The job running on runner GitHub Actions 36 has exceeded the maximum execution time of 30 minutes.

**Comment by billyvg** [comment]
@jan-auer pypy is super slow, and 3.7 seems to also be failing (not just timing out)

**Comment by untitaker** [comment]
I have concerns about the severe slowdown in gha. Does this still pay off financially?

I fixed master and restarted the build. If it is green feel free to merge anytime 

(yes we need to fix the testsuite itself too - - though I don't have any ideas atm. If you have opinions lmk and we can brainstorm on slack)

**Comment by billyvg** [comment]
@untitaker yeah staying on travis is not an option for our active repos - I think if speed is an issue going forward, we can maybe parallelize? Not sure if that's doable with tox

**Pull request merged**
