### PR TITLE
Handle iteration errors during frame traversal

### LINKED ISSUE #238: Event is dropped if Exception occurs during `object_to_json`
This may happen if Sequence is Django queryset that has incorrect field in `filter()` expressions.

### PR DESCRIPTION
**Pull request by leotrubach**
Fixes #238

Not sure if this is the best way to show it, i think it is better than showing just empty list. But maybe there could be some better way to show that exception occured during traversal.

There is more general problem that it is probably good to not iterate over queryset, so DB is not queried. Any ideas on how to do that?

### CODE REVIEW

**Comment by untitaker** [comment]
I believe it would be appropriate to only traverse builtin collections (check for `isinstance(x, (tuple, list))`) and just stringify the rest like arbitrary objects

**Comment by untitaker** [comment]
Cool, could you add an explanatory comment as well?

**Comment by leotrubach** [comment]
@untitaker Do you mean comment to code or commit message?

**Comment by untitaker** [comment]
in the code :) thanks!

**Comment by untitaker** [comment]
Awesome thanks!

**Pull request merged**
