### PR TITLE
Add the stack option back to the Logging integration

### PR DESCRIPTION
**Pull request by jrideout**
In Raven, you could do this:

```
logger.warning('things happened', extra={'stack': True})
```

And the stack would be collected. This adds back that feature.

### CODE REVIEW

**Comment by untitaker** [comment]
@jrideout thanks! I believe we want to somehow expose this on the scope instead of having special options on the logger though. That approach did not scale well in Raven.

**Comment by untitaker** [comment]
@jrideout we have these scopes to override default values:

```
with push_scope() as scope:
    scope.fingerprint = ['foobar']

    capture_exception()  # custom fingerprint

capture_exception()  # no custom fingerprint
```

I wonder whether we can use scopes here too:

```
with push_scope() as scope:
    scope.attach_stacktrace = True

    logger.error(...)


```

I realize this is not optimal but I want to get rid of the weird arguments on logging calls

**Comment by jrideout** [comment]
What about using `exc_info=True` for the non-exception use case as well? That would give a consistent user experience.

**Comment by untitaker** [comment]
I like that idea, not sure if we have this info. @mitsuhiko what do you think?

**Comment by untitaker** [comment]
Let's keep this open, I will check it out tomorrow

**Comment by jrideout** [comment]
oops, I don't know how I closed this, I didn't mean too!

**Comment by untitaker** [comment]
Thanks!

**Pull request merged**
