### PR TITLE
chore(deps): update urllib3 minimum version

### PR DESCRIPTION
**Pull request by miketheman**
The current constraint expresses at least urllib3 version 1.10.0,
which has at least 5 CVEs open.

Projects relying on `sentry-sdk` will get an optimistic version of
the latest, so current test suites are already using the latest version
which patches these vulnerabilities.

Refs:

- https://github.com/advisories/GHSA-www2-v7xj-xrc6 (critical)
- https://github.com/advisories/GHSA-mh33-7rrq-662w (high)
- https://github.com/advisories/GHSA-hmv2-79q8-fv6g (high)
- https://github.com/advisories/GHSA-wqvq-5m8c-6g24 (moderate)
- https://github.com/advisories/GHSA-5phf-pp7p-vc2r (moderate)

Signed-off-by: Mike Fiedler <miketheman@gmail.com>

### CODE REVIEW

**Comment by miketheman** [comment]
@sl0thentr0py any chance for a review here? It's be nice to close out some if these security issues.

**Comment by miketheman** [comment]
Test fails for Python 3.4 - how long are you planning on supporting legacy versions?

**Comment by sl0thentr0py** [comment]
Hi @miketheman, we're looking into dropping 3.4 but we need to follow some deprecation process first, will get back to you when I know more.

**Comment by miketheman** [comment]
@sl0thentr0py any chance of coming back to this?

**Review by antonpirker — APPROVED** [review]

**Review by sl0thentr0py — APPROVED** [review]
thx @miketheman and sorry for the delay.
getting rid of 3.4 will still take some time due to our 'support everything' policy internally but I've added conditional markers according to [PEP 508](https://peps.python.org/pep-0508/#environment-markers) which should make this a bit better for the overall ecosystem security wise.

**Comment by miketheman** [comment]
Thanks @sl0thentr0py ! Looking forward to the release and closing the vulnerable alerts.

**Pull request merged**
