### PR TITLE
feat: Add debug log support in client init

### PR DESCRIPTION
**Pull request by mitsuhiko**

### CODE REVIEW

**Comment by untitaker** [comment]
Ok, then why not when the client is bound to a hub? Integrations are ineffective anyway if the client isn't bound to a hub.

**Comment by mitsuhiko** [comment]
What's the benefit of doing that? I just worry this is going to make things worse for no obvious benefit.

**Comment by untitaker** [comment]
I'm just suggesting it as alternative to this one. I don't see drawbacks for either.

**Comment by untitaker** [comment]
@mitsuhiko any opinion on my proposal? I don't really care anymore

**Comment by mitsuhiko** [comment]
@untitaker i am considering it. i think debug logging is a bit stupid right now for more than one reason so it would be good to change it. eg: debug messages from the transport are suppressed.

**Comment by untitaker** [comment]
I don't think we can make a single API change that fixes both cases in case that's what you're aiming for.

**Comment by mitsuhiko** [comment]
@untitaker no, but when making the logger explicit (eg: per hub) this PR becomes pointless.

**Comment by untitaker** [comment]
I'm not a big fan of this idea because it's incompatible with how we use
logging. dictConfig in sentry (where we explicitly install a sentry handler
on sentry_sdk.errors

**Comment by untitaker** [comment]
@mitsuhiko I'm actually fine with this as-is. Do you have any concerns?

**Comment by mitsuhiko** [comment]
WFM. We can still clean it up later. It's just that it does not solve the issue that transports don't log.

**Pull request merged**
