### PR TITLE
Create Scope.set_extras

### PR DESCRIPTION
**Pull request by Marcelo-Theodoro**
The idea is to add a method that makes easy to add more than one `extra` at the same time.

### CODE REVIEW

**Comment by untitaker** [comment]
Could you add this consistently for `set_tags` etc too? We already have this in the [JS SDK](https://github.com/getsentry/sentry-javascript) and I believe it would be good if it worked the same (so close!)

**Comment by untitaker** [comment]
Also please add global methods like in #540

**Comment by Marcelo-Theodoro** [comment]
Sure!!
I'll work on it tomorrow, is that ok?
Thanks.

**Comment by untitaker** [comment]
Of course!

**Pull request closed without merging**
