### PR TITLE
Improve typings some

### LINKED ISSUE #386: Some code structures are not conducive to static typing
This package now declares that it includes typings so I tried to whitelist it in one of my projects. Unfortunately I got various errors like `error: Module has no attribute "push_scope"` for `sentry_sdk.push_scope()`.

I haven't tried it but I suspect that dynamic code structures like

https://github.com/getsentry/sentry-python/blob/64ca9a97fcfe342b0ef080532b1b0574f8655d68/sentry_sdk/__init__.py#L35-L43

https://github.com/getsentry/sentry-python/blob/64ca9a97fcfe342b0ef080532b1b0574f8655d68/sentry_sdk/api.py#L24-L52

are too hard for mypy to understand. I was wondering if you'd be willing to forgo these (nice) shortcuts in order to help mypy. I'll be happy to send a PR if so.

### PR DESCRIPTION
**Pull request by bluetech**
The first commit fixes #386.

The second commit is a bug fix that mypy found.

The third commit adds a basic example as requested in https://github.com/getsentry/sentry-python/issues/386#issuecomment-499010982.

The fourth commit improves the typings a bit by enabling some more strict mypy options and fixing the errors. I imagine it's quite hard to review so I can leave it off if that's preferable.

### CODE REVIEW

**Comment by bluetech** [comment]
I marked the PR as a draft because the fourth commit still has some errors (all in same spirit), and I don't know for sure what is the proper fix:

```
sentry_sdk/integrations/threading.py:60: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/rq.py:49: error: Item "None" of "Optional[Client]" has no attribute "flush"
sentry_sdk/integrations/rq.py:100: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/excepthook.py:42: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/atexit.py:51: error: Item "None" of "Optional[Client]" has no attribute "close"
sentry_sdk/integrations/tornado.py:114: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/sanic.py:139: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/aws_lambda.py:34: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/aws_lambda.py:50: error: Item "None" of "Optional[Client]" has no attribute "flush"
sentry_sdk/integrations/pyramid.py:131: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/falcon.py:127: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/bottle.py:105: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/django/__init__.py:229: error: Item "None" of "Optional[Client]" has no attribute "options"
sentry_sdk/integrations/flask.py:181: error: Item "None" of "Optional[Client]" has no attribute "options"
```

These happen because `Hub.client` has type `Optional[Client]`, but the code assumes it is not None. Possible fixes are:

1. Change the type of `Hub.client` to not be optional? Can it be None?
2. Add `assert client is not None` before each call site.
3. Raise an error if client is None.

Once this is decided this can go through CI (I only tested basic py3.7 configuration).

**Comment by untitaker** [comment]
>Change the type of Hub.client to not be optional? Can it be None?

It can be `None`, but if there is an integration available there must be a client available.

I "fixed" it by casting the type to `Any` 😬. I didn't feel like doing something on runtime, like an assertion or `typing.cast`.

Thanks, this is great work

**Comment by untitaker** [comment]
I hope you find the changes acceptable... since the `Any` cast is somewhere deep in internals it shouldn't matter to the user.

btw, are you interested in joining the community Slack channel for the SDK?

**Comment by bluetech** [comment]
> I hope you find the changes acceptable...

Yes, they look good to me.

> btw, are you interested in joining the community Slack channel for the SDK?

I don't use Slack personally. If I run into further issues with the typings I'll be sure to return with a PR though :)

**Comment by untitaker** [comment]
Thanks so far!

**Pull request merged**
