### PR TITLE
Add badges to Readme

### PR DESCRIPTION
**Pull request by peleccom**
Add pypi package version badge
Add package licence Badge

### CODE REVIEW

**Comment by untitaker** [comment]
If you think some information is missing from the README I would suggest to add regular links. My experience with them is that their text is cryptic and that they impact page load perf.

**Comment by peleccom** [comment]
You could add just pypi version badge only to be aligned with sdk package for other languages, python-raven had this information too.

Currently, Readme file of this repository is poor. There are no module usage examples. No current version information. The first impression was it is not usable at all.

**Comment by untitaker** [comment]
@peleccom Thanks for the feedback. I didn't want to duplicate information found elsewhere. I will add a small example though and I agree the current version does make sense to show.

**Comment by untitaker** [comment]
trying to figure out what to do here:

* I actually like the version badge now
* https://sentry.io/for/python/ is the perfect readme for the sdk, but I don't know if I should just copypaste it into the code. Problem is that for each framework you need to do more things, so the basic example without integrations is often useless

**Comment by untitaker** [comment]
Thanks for your input, I think the README should be good now. I am still not sure if this will be misleading as a user often has to set up integrations to see anything.

**Pull request closed without merging**
