### PR TITLE
ref: Update transaction status to match final protocol

### PR DESCRIPTION
**Pull request by untitaker**
schema def here: https://github.com/getsentry/semaphore/pull/326

### CODE REVIEW

**Comment by untitaker** [comment]
Since nobody reviews this I'll just merge it.

**Comment by dashed** [comment]
Since it got merged, let's say I "approved" it 😎 .

**Comment by kamilogorek** [comment]
I did reviewed it.

**Comment by dashed** [comment]
@untitaker will this land in SaaS soon? 😄

**Pull request merged**
