### PR TITLE
Removed datetime_from_timestamp ...

### PR DESCRIPTION
**Pull request by antonpirker**
... and replaced it with the native `datetime.fromtimestamp`.

### CODE REVIEW

**Review by sentrivana — COMMENTED** [review]
We can remove the function itself too, and replace the last remaining usage in https://github.com/getsentry/sentry-python/blob/dce589ca49a8e0e2d4eda3839836de6d8188f17b/sentry_sdk/scope.py#L1324 with standard `datetime.fromisoformat`

**Review by sentrivana — APPROVED** [review]
Looks good but let's also remove the util (see comment above)

**Comment by antonpirker** [comment]
I guess `datetime_from_isoformat` is already gone in `potel-base` branch so I will merge this.

**Comment by sentrivana** [comment]
Ah gotcha I think I was looking at master. 👍🏻

**Pull request merged**
