### PR TITLE
WIP port aiohttp transports from raven_aiohttp

### PR DESCRIPTION
**Pull request by tonal**
I do not understand how to correct close this transports

### CODE REVIEW

**Comment by untitaker** [comment]
Why do you need the aiohttp transport?

**Comment by untitaker** [comment]
@tonal interesting. Do you no longer experience issues with this transport? We could try to figure out how to set a different transport from integrations (we might need this for AWS Lambda anyway) and then use this.

Thanks for working on this! I still don't understand what's happening though. Why does asyncio freeze up when something spawns its own thread?

What are the speed differences you see? Does your transport send stuff in parallel? This is something we explicitly don't want, because you would get rate-limited anyway.

**Comment by cancan101** [comment]
Any updates on this or an async transport? I am using starlette and would prefer to use non blocking / async transports.

**Comment by untitaker** [comment]
@cancan101 as said the transport should be non-blocking because it runs on a dedicated OS thread. Of course there are better ways to achieve parallelism in async but this method works in both async/sync and we only spawn one extra thread.

**Comment by untitaker** [comment]
I'm going to close this because it is WIP and inactive for quite a while now. I would probably be open to having one alternative transport if the speed is really so much better though. But before that I'd like to see it working.

**Pull request closed without merging**
