### PR TITLE
Pin `grpcio` versions in CI

### PR DESCRIPTION
**Pull request by arr-ee**
From https://github.com/getsentry/sentry-python/issues/2721#issuecomment-1969084637

This PR pins `grpcio` versions instead of `grpcio-tools`, as well as restructures test matrix and fixes an issue in grpc integration with `grpcio < 1.40` exposed by the fixed tests.

- `grpcio` versions for each "major" (1.xx.y) were bumped to the latest in the respective "major", e.g. `~=1.30.0` => `~=1.39.0`.
    This was done to work around [various](https://github.com/grpc/grpc/pull/28398) [build](https://github.com/grpc/grpc/issues/25112) and [runtime](https://github.com/grpc/grpc/issues/27888) issues present in earlier versions.
- max python version for `grpcio` < 1.40 (< 1.42 actually) was lowered to cpy3.9 due to https://github.com/grpc/grpc/issues/27888

There is an unresolved issue with `grpcio-1.2x.y`: `grpc.aio` module only got moved out of `grpc.experimental` in 1.32.0 (see https://github.com/grpc/grpc/pull/23240). Whether it is worth supporting this case is not for me to decide :)

---

## General Notes

Thank you for contributing to `sentry-python`!

Please add tests to validate your changes, and lint your code using `tox -e linters`.

Running the test suite on your PR might require maintainer approval. Some tests (AWS Lambda) additionally require a maintainer to add a special label to run and will fail if the label is not present.

#### For maintainers

Sensitive test suites require maintainer review to ensure that tests do not compromise our secrets. This review must be repeated after any code revisions.

Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before running sensitive tests.

### CODE REVIEW

**Comment by arr-ee** [comment]
Note: getting older `grpcio` releases to build, especially without bumping them from `1.x0.0`, can be non-trivial. I ended up pre-building wheels using `cibuildwheel`, e.g.:

```shell
pipx install cibuildwheel
pip download --no-binary=:all: 'grpcio~=1.20;<1.30'
tar xzvf grpcio-1.29.0.tar.gz
CIBW_BUILD="cp3{7,9,10}-many*" cibuildwheel --platform linux --archs aarch64 grpcio-tools-1.29.0
```

This might be an issue with building wheels in CI during `pip install` since e.g. https://github.com/grpc/grpc/pull/18950 means grpcio < 1.33.1 won't build on many modern linux distros.

**Comment by arr-ee** [comment]
CI failures are `grpc.aio` tests for `grpcio-1.29` that I mentioned in the description; I suggest we drop this test target for now and reintroduce it in a separate issue (if at all)

**Comment by sentrivana** [comment]
@arr-ee This is great, thanks for your work on this!

The changes look good to me. Since we're _technically_ dropping support for some `grpcio` versions, I'd prefer we merge this into the `sentry-sdk-2.0` branch where we're working on the 2.0 major instead of `master`.

**Comment by arr-ee** [comment]
sgtm — let me know if you want me to update the pr for 2.0 or if you’d rather take care of it yourself

**Comment by sentrivana** [comment]
Merged to 2.0 now -- now we'll only have to live with the tests being slow on `master` for a couple weeks until we merge the 2.0 branch. Thanks again!

**Pull request merged**
