### PR TITLE
feat(integrations): Add support for celery-redbeat cron tasks

### LINKED ISSUE #2616: Automatically create monitors when using Redbeat
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We're using Python with [Celery] and [Redbeat] and following the [docs] for setup. Using _either_ the autodiscover or manual `@monitor` instrumentation outlined in the docs, we are not having monitors in our Sentry UI automatically created. But manually creating them confirms that the data does come into Sentry—as soon as they're created we can see data for them in the UI, but only from that point forward.

I've been talking to Sentry support about this and was asked to create an Issue. Unfortunately our repo is private but our setup is pretty straightforward. Here's the gist of what we've got:

`requirements.txt`:

```
celery==5.2.6
celery-redbeat==2.0.0
```

`worker.py`

```py
from celery import Celery
from celery.signals import celeryd_init
from celery.schedules import crontab
import sentry_sdk
from sentry_sdk.crons.decorator import monitor
from sentry_sdk.integrations.celery import CeleryIntegration

from myco import _my_celery_task, get_env_var, LockInUse, get_redis_url

app = Celery(__name__, broker=get_redis_url(database='celery'))

@celeryd_init.connect
def init_sentry(**_kwargs):
    env = get_env_var('APP_ENV', False)
    if not env:
        print('APP_ENV not set, defaulting to development')
        env = 'development'
    if env not in ['development', 'test']:
        sentry_sdk.init(
            dsn="<DSN@ingest.sentry.io>", # obviously this is redacted

            environment=env,
            release=get_env_var('SENTRY_RELEASE_VERSION', False) or 'unknown',

            ignore_errors=[LockInUse],

            integrations=[CeleryIntegration()],

            # Set traces_sample_rate to 1.0 to capture 100%
            # of transactions for performance monitoring.
            # We recommend adjusting this value in production,
            traces_sample_rate=0.005,
        )

# ...


@app.task
@monitor(monitor_slug='my_celery_task')
def my_celery_task():
    return _my_celery_task()

# ...

app.conf.redbeat_redis_url = get_redis_url(database='celery')
app.conf.beat_scheduler = 'redbeat.RedBeatScheduler'
app.conf.beat_schedule = {
    'my-celery-task': {
        'task': 'worker.my_celery_task',
        'schedule': crontab(minute='0', hour='0', day_of_week='1'),
    },
    # ...
}
```

[celery]: https://docs.celeryq.dev/en/stable/
[redbeat]: https://pypi.org/project/celery-redbeat/
[docs]: https://docs.sentry.io/platforms/python/crons/

### Expected Result

Cron job monitors are automatically created in Sentry on deploy, or at least when they execute

### Actual Result

No monitors are created

### Product Area

Crons

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by kwigley**
This add support for celery-redbeat (resolves #2616). Thanks to https://github.com/getsentry/sentry-python/issues/2616#issuecomment-1875438310

---

## General Notes

Thank you for contributing to `sentry-python`!

Please add tests to validate your changes, and lint your code using `tox -e linters`.

Running the test suite on your PR might require maintainer approval. Some tests (AWS Lambda) additionally require a maintainer to add a special label to run and will fail if the label is not present.

#### For maintainers

Sensitive test suites require maintainer review to ensure that tests do not compromise our secrets. This review must be repeated after any code revisions.

Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before running sensitive tests.

### CODE REVIEW

**Comment by sentrivana** [comment]
Thanks a lot @kwigley! We will take a look.

**Comment by sentrivana** [comment]
Hey @kwigley, sorry for the wait.

I've tried the PR but it doesn't work for me -- did it work for you? As far as I can tell the problem is we attempt to patch the `RedBeatScheduler` class, but we're not patching it in the right place or at the right time, because when I run this, only the original `maybe_due` is called, but not our wrapped one. Lmk if the code worked for you as is -- in that case it might be something with my setup.

**Comment by sentrivana** [comment]
Ok it was a problem with my setup (and our docs :) ) -- I'm getting monitors now. Will give the PR one more look but looks good at first glance!

**Review by sentrivana — APPROVED** [review]

**Comment by kwigley** [comment]
> Ok it was a problem with my setup (and our docs :) ) -- I'm getting monitors now. Will give the PR one more look but looks good at first glance!

ah, missed your previous comment. Sounds good! lmk if you need anything else

**Comment by sentrivana** [comment]
@kwigley All good, no action needed on your end, this is good to merge. Thank you!

**Pull request merged**
