### PR TITLE
Replace PyPI page with README.md

### PR DESCRIPTION
**Pull request by cclauss**
https://pypi.org/project/sentry-sdk/ is currently a bit too spartan and requires the user to do extra clicks to determine if they want to install or upgrade this package.

This PR proposes to replace the current one-liner with the markdown content from `README.md`.

### CODE REVIEW

**Comment by untitaker** [comment]
Is there a place where we can figure out which constructs are supported in pypi? We have some html in the readme

**Comment by cclauss** [comment]
https://github.com/pypa/warehouse is the place to open/read issues on these topics.

You can always [push a trial version to the ___testpypi___ server](https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives) with `python3 -m twine upload --repository testpypi dist/*`.  This will go to a test server instead of the public PyPI so you can see if/how the HTML renders.  Also, check the relative links in markdown.  These might need to be converted to absolute links to work correctly on PyPI.

My first commit tried to add CHANGES.md to the end but that file is not available.

**Comment by untitaker** [comment]
Thanks! 👍

**Comment by cclauss** [comment]
Which repo contains the Sentry web user interface or is that not open source?

**Comment by untitaker** [comment]
That's getsentry/sentry. I think you already contributed to it :)

**Pull request merged**
