### PR TITLE
all-repos: update actions/upload-artifact to v4

### PR DESCRIPTION
**Pull request by joshuarli**
Committed via https://github.com/asottile/all-repos

### CODE REVIEW

**Comment by sentrivana** [comment]
Looks like [there's a 409 being thrown](https://github.com/getsentry/sentry-python/actions/runs/10180537705/job/28158620810?pr=3381) with the new `upload-artifact` -- might be we are affected by https://github.com/actions/upload-artifact/issues/478. I see folks in the thread solving this by giving the artifact a unique name. We need to look into this soon since v3 is getting deprecated.

**Comment by joshuarli** [comment]
> Looks like [there's a 409 being thrown](https://github.com/getsentry/sentry-python/actions/runs/10180537705/job/28158620810?pr=3381) with the new `upload-artifact` -- might be we are affected by [actions/upload-artifact#478](https://github.com/actions/upload-artifact/issues/478). I see folks in the thread solving this by giving the artifact a unique name. We need to look into this soon since v3 is getting deprecated.

Yup, a unique name is what's needed. I propose `${{ github.sha }}-dist` and `${{ github.sha }}-gh-pages`, what do you think?

Also, it would be better to save on some unnecessary(?) work if upload-artifact were skipped if it's a PR branch. Let me know if you want me to do that.

**Comment by sentrivana** [comment]
@joshuarli Both suggestions sound good to me. I guess instead of renaming we could also do [`overwrite: true`](https://github.com/actions/upload-artifact/blob/9d63e3f2f81d9dc4e13d83fc330408f8a94b79d1/docs/MIGRATION.md#overwriting-an-artifact)?

**Comment by joshuarli** [comment]
> @joshuarli Both suggestions sound good to me. I guess instead of renaming we could also do [`overwrite: true`](https://github.com/actions/upload-artifact/blob/9d63e3f2f81d9dc4e13d83fc330408f8a94b79d1/docs/MIGRATION.md#overwriting-an-artifact)?

a new artifact id will still be created, i'm not yet sure if that'll affect craft (probably it will), see https://github.com/getsentry/craft/issues/552

**Comment by joshuarli** [comment]
Superseded by https://github.com/getsentry/sentry-python/pull/3545.

**Pull request closed without merging**
