### PR TITLE
Add shell control in options

### PR DESCRIPTION
**Pull request by tolgahanuzun**
Description : https://github.com/getsentry/sentry-python/issues/360

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks for your PR! Would you mind making this an option on the integration, like the options on e.g. `FlaskIntegration`?

**Comment by tolgahanuzun** [comment]
I think the integration could be this way. Isn't that right?

```python3
import sentry_sdk
sentry_sdk.init(
    'http.....',
    debug=True,
    is_shell_active=True,
)
```

**Comment by untitaker** [comment]
@tolgahanuzun My point is that this global setting is not used by any other integration. To configure `transaction_style` for the `FlaskIntegration`, you run this:

```python
sentry_sdk.init(
    ...,
    integrations=[FlaskIntegration(transaction_style="...")]
)
```

And I think it should work the same for this integration, because it's really only something the integration uses.

**Comment by untitaker** [comment]
You can send events with `capture_event` and other integrations. I have trouble imagining where you'd be fine with a `NameError` being sent to Sentry:

```
>>> foo = 42
>>> fooo
NameError: ...
```

**Comment by untitaker** [comment]
>In every situation, this should be a configurable parameter, not hard coded.

We will not add configurable options without a reason, especially not on the client object. You write:

>We need to send events to Sentry working in REPL.

And I don't understand why that is desirable. A REPL session is full of typos and broken code that you then rerun immediately. Why do you want to add all of that into Sentry?

In any case it seems nowhere near a popular enough usecase to have this as param on `init`.

**Comment by untitaker** [comment]
>We need to send events to Sentry working in REPL.

Again, why is this desirable behavior?

**Comment by tolgahanuzun** [comment]
`In any case it seems nowhere near a popular enough usecase to have this as param on init.`
Well then, thank you. :) You can close Pr.

**Comment by untitaker** [comment]
@tolgahanuzun To be clear I would be happy to have this on the integration object, but we are more careful with direct args on `init`

**Pull request closed without merging**
