### PR TITLE
Ref: Add `include_source_context` option in utils

### LINKED ISSUE #2017: Add `include_source_context` option
### Problem Statement

Some users do not like the source context to be there and want to disable it.

### Solution Brainstorm

For this we need to add a SDK option `include_source_context` that defaults to `True`.
If set to false, the source context should not be included.

Here is probably the place where to decide whether to add the source context or not: 
https://github.com/getsentry/sentry-python/blob/antonpirker/celery-beat-wo-restart/sentry_sdk/utils.py#L614-L625

### PR DESCRIPTION
**Pull request by farhat-nawaz**
- Added `include_source_context` option to `serialize_frame` function to allow users to opt-out of getting source context.

This is my very first open-source contribution. Please let me know if I missed something.

Fixes #2017

### CODE REVIEW

**Comment by antonpirker** [comment]
Hey @farhat-nawaz !

Thanks for the contribution! Looks good!

Now we also need the `include_source_context` option in `ClientConstructor` class at the end and need to pass this option along so that all calls to `serialize_frame` are given the option set in `ClientConstructor`. (you can see   `include_local_variables` for a similar option)

**Comment by antonpirker** [comment]
If you do not have time it is also possible that we merge this and take over the rest of the implementation. Should we do this?

**Comment by farhat-nawaz** [comment]
@antonpirker Sure, I can add those changes, no problem.

**Comment by sentrivana** [comment]
Hey @farhat-nawaz, thanks again for contributing! Did you already have time to start on the changes that Anton proposed? If not, I'm happy to take it from here and finish it.

**Comment by sentrivana** [comment]
Hi @farhat-nawaz, the PR looks good to me, I will merge it now as is and we'll add the missing stuff. Thank you for contributing! 🙏

**Comment by farhat-nawaz** [comment]
@sentrivana Glad to have made the contribution, and looking forward to more. Sorry about not being able to respond earlier, something unexpected came up. :)

**Pull request merged**
