### PR TITLE
feat(integration): Add Httpx Integration

### LINKED ISSUE #1084: integration for httpx
About [httpx](https://github.com/encode/httpx/):

> HTTPX is a fully featured HTTP client for Python 3, which provides sync and async APIs, and support for both HTTP/1.1 and HTTP/2.

About integration:

Currently, sentry has integration for `httplib` but httpx has its own transport layer and [we can customize the transport layer if we needed](https://www.python-httpx.org/advanced/#custom-transports). 

About implementation:

We can patch `Client.send` and `AsyncClient.send` to support both synchronous and async interfaces.

I already write this integration for internal use, I will make a pr if you want to accept this feature.

### PR DESCRIPTION
**Pull request by elonzh**
close #1084

### CODE REVIEW

**Comment by ahmedetefy** [comment]
Hey Thanks for the PR! It looks good!

Just a couple of minor points:
1- Can you add a test for outgoing trace headers?
For reference something like -> https://github.com/getsentry/sentry-python/blob/4b4ffc05795130c8a95577074a29462c2a512d66/tests/integrations/stdlib/test_httplib.py#L120

2- Please document your code and tests

**Comment by elonzh** [comment]
> Hey Thanks for the PR! It looks good!
> 
> Just a couple of minor points:
> 1- Can you add a test for outgoing trace headers?
> For reference something like ->
> 
> https://github.com/getsentry/sentry-python/blob/4b4ffc05795130c8a95577074a29462c2a512d66/tests/integrations/stdlib/test_httplib.py#L120
> 
> 2- Please document your code and tests

check out the new commit

**Comment by ahmedetefy** [comment]
Thanks for looking into my comments!

Please add a `type: ignore` comment to the `httpx` imports line to pass the linter tests

**Comment by elonzh** [comment]
> Thanks for looking into my comments!
> 
> Please add a `# type: ignore` comment to the `httpx` imports line to pass the linter tests

Done.

**Review by ahmedetefy — APPROVED** [review]

**Pull request merged**
