### PR TITLE
Get rid of setup.cfg by moving the only option to setup.py

### PR DESCRIPTION
**Pull request by hynek**
🎉

### CODE REVIEW

**Review by untitaker — APPROVED** [review]
Thanks, I didn't know you can do that!

**Comment by hynek** [comment]
Python packaging is a land full of mysteries. ;)

I've been told it once by the maintainers in connection with my PyPI blog post.

**Comment by untitaker** [comment]
Do you know by chance when this feature was introduced? I mean, seems to run fine on last pip for 2.7, but we have people running on 2.6.

**Comment by hynek** [comment]
I don't think this is a pip feature but a setuptools/wheel one.

Assuming it's a recent-ish features (which I don't think), it would only affect people who insist on building their sdists with ancient build chains into wheels.

**Comment by untitaker** [comment]
Fair enough.

**Pull request merged**
