### PR TITLE
The Falcon integration for Falcon 3.0.1

### PR DESCRIPTION
**Pull request by bartolootrit**
The Falcon integration passed the tests for Falcon 3.0.1, 2.0.0, 1.4.0 (Python 3.8) and Falcon 2.0.0, 1.4.0 (Python 2.7)

### CODE REVIEW

**Comment by pecalleja** [comment]
any news about this ?

**Comment by antonpirker** [comment]
Hello @bartolootrit !
Thanks for your contribution!

We also got an PR for Falcon 3.0.0 from @Seluj78:
https://github.com/getsentry/sentry-python/pull/1073

Could you @bartolootrit talk to @Seluj78 on how you can merge the two PRs into one? So we have only one Falcon Integration that we can review and eventually merge?

**Comment by antonpirker** [comment]
Maybe also @pecalleja could help somehow?

**Comment by Seluj78** [comment]
https://github.com/getsentry/sentry-python/pull/1073 was closed. Are my changes from there in here ? :)

**Comment by antonpirker** [comment]
Hey @Seluj78 
I am not sure if your changes are in here (or what your changes are, to be precise ;-) )
Could you have a look at the files changed to see if they are here: https://github.com/getsentry/sentry-python/pull/1297/files ?

**Comment by antonpirker** [comment]
FYI @bartolootrit and @Seluj78 

I have now added Falcon 3.0.0 and 3.1.0 to our test suite here:
https://github.com/getsentry/sentry-python/pull/1378

If all the tests for this are green I can merge this into master and then you can rebase your pull request onto the new master, so we can run all our tests in Falcon 3.0 and 3.1!

**Comment by Seluj78** [comment]
Looking good, it just seems like the imports are differently named now ? https://github.com/getsentry/sentry-python/pull/1073/files#diff-af8d1eba8feb85336f0d9a1a04a78beaa87da4a8efa675b478a18b8f603d63f8R20

**Comment by bartolootrit** [comment]
[antonpirker](https://github.com/antonpirker)
Ok. I'll rebase this pull request after https://github.com/getsentry/sentry-python/pull/1378 has been merged.

**Comment by antonpirker** [comment]
Hey @bartolootrit !

Turns out I can not merge https://github.com/getsentry/sentry-python/pull/1378 because it fails (because it has not Falcon 3 support) :-)

So I changed this PR to be merge into the branch with the Tests. Lets see how this turns out. 
If there are errors, you can try to fix them in your branch and push again, the tests should be triggered again.

**Comment by bartolootrit** [comment]
@antonpirker I've rebased this branch. An approval is needed to run workflows.

**Comment by Omnia6975** [comment]
The doc still say that it is compatible only with  1.4 and 2.0 only
[https://docs.sentry.io/platforms/python/guides/falcon/](https://docs.sentry.io/platforms/python/guides/falcon/)
`The Falcon integration adds support for the [Falcon Web Framework](https://falconframework.org/). The integration has been confirmed to work with Falcon 1.4 and 2.0`

Could you please confirm that it is now compatible with falcon 3.0.1 ?

**Comment by Omnia6975** [comment]
Is there any reason why this pull requests has never been done ?

**Comment by Omnia6975** [comment]
Why this pull request has never been merged ? Could be great to have falcon 3 support !

**Pull request merged**
