### PR TITLE
Add transaction styling for aiohttp integration

### PR DESCRIPTION
**Pull request by asovchar**

### CODE REVIEW

**Comment by untitaker** [comment]
I doubt using *path* is generally useful. It can contain a lot of extra data that varies between requests. I would go for using the route pattern instead.

**Review by untitaker — APPROVED** [review]

**Comment by untitaker** [comment]
thx, can you fix flake8 errors?

https://travis-ci.com/github/getsentry/sentry-python/jobs/401912287

**Comment by asovchar** [comment]
@untitaker Done

**Comment by untitaker** [comment]
Can you file a PR against https://github.com/getsentry/sentry-docs for documenting this? In the meantime I will merge this, thanks!

**Comment by asovchar** [comment]
https://github.com/getsentry/sentry-docs/pull/2546

**Comment by vmarkovtsev** [comment]
This is so useful, thanks!

**Pull request merged**
