### PR TITLE
Updated Falcon integration to support Falcon 3.0.0

### PR DESCRIPTION
**Pull request by Seluj78**
As discussed here: https://github.com/falconry/falcon/issues/1898#issuecomment-813931836

### CODE REVIEW

**Comment by vytas7** [comment]
FWIW, the module in question was removed (renamed) by oversight: https://github.com/falconry/falcon/issues/1902

**Comment by pecalleja** [comment]
any news about this?

**Comment by antonpirker** [comment]
Hello @Seluj78 !
Thanks for your contribution!

We also got an PR for Falcon 3.0.1 from @bartolootrit:
https://github.com/getsentry/sentry-python/pull/1297

Could you @Seluj78 talk to @bartolootrit on how you can merge the two PRs into one? So we have only one Falcon Integration that we can review and eventually merge?

Thanks!

**Comment by antonpirker** [comment]
Maybe also @pecalleja could help somehow?

**Comment by pecalleja** [comment]
@antonpirker Yes, I would love to help !!! do you need help to test the solution 
or 
to review both PR and try to merge both in one?

**Comment by bartolootrit** [comment]
If I open a pull request from [bartolootrit:falcon-3-integration](https://github.com/bartolootrit/sentry-python/tree/falcon-3-integration) into [Seluj78:patch-1](https://github.com/Seluj78/sentry-python/tree/patch-1), it will just overwrite all changes in [Seluj78:patch-1](https://github.com/Seluj78/sentry-python/tree/patch-1). What else can we do?

**Comment by Seluj78** [comment]
What you can do is just create a new branch from `master` and copy manually the changes from the different PRs :)

**Comment by bartolootrit** [comment]
> What you can do is just create a new branch from `master` and copy manually the changes from the different PRs :)

A new PR after this process would be equal to [#1297](https://github.com/getsentry/sentry-python/pull/1297). If it's expected, then this PR might be closed, if not, what should I change in [#1297](https://github.com/getsentry/sentry-python/pull/1297)?

**Comment by sl0thentr0py** [comment]
@bartolootrit cool then let's just continue in #1297.

**Pull request closed without merging**
